# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'applicationUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 573)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodCombo.sizePolicy().hasHeightForWidth())
        self.methodCombo.setSizePolicy(sizePolicy)
        self.methodCombo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.methodCombo.setObjectName("methodCombo")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.methodCombo.addItem("")
        self.horizontalLayout.addWidget(self.methodCombo)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.functionLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.functionLineEdit.setObjectName("functionLineEdit")
        self.horizontalLayout.addWidget(self.functionLineEdit)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(18, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.EpslineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EpslineEdit.sizePolicy().hasHeightForWidth())
        self.EpslineEdit.setSizePolicy(sizePolicy)
        self.EpslineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.EpslineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.EpslineEdit.setAutoFillBackground(False)
        self.EpslineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.EpslineEdit.setDragEnabled(True)
        self.EpslineEdit.setPlaceholderText("Default : 0.05")
        self.EpslineEdit.setClearButtonEnabled(False)
        self.EpslineEdit.setObjectName("EpslineEdit")
        self.horizontalLayout_9.addWidget(self.EpslineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.iterlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iterlineEdit.sizePolicy().hasHeightForWidth())
        self.iterlineEdit.setSizePolicy(sizePolicy)
        self.iterlineEdit.setObjectName("iterlineEdit")
        self.horizontalLayout_8.addWidget(self.iterlineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelX0 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelX0.sizePolicy().hasHeightForWidth())
        self.labelX0.setSizePolicy(sizePolicy)
        self.labelX0.setMinimumSize(QtCore.QSize(20, 0))
        self.labelX0.setBaseSize(QtCore.QSize(20, 12))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelX0.setFont(font)
        self.labelX0.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX0.setObjectName("labelX0")
        self.horizontalLayout_5.addWidget(self.labelX0)
        self.X0lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X0lineEdit.sizePolicy().hasHeightForWidth())
        self.X0lineEdit.setSizePolicy(sizePolicy)
        self.X0lineEdit.setObjectName("X0lineEdit")
        self.horizontalLayout_5.addWidget(self.X0lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelX1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelX1.sizePolicy().hasHeightForWidth())
        self.labelX1.setSizePolicy(sizePolicy)
        self.labelX1.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelX1.setFont(font)
        self.labelX1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelX1.setObjectName("labelX1")
        self.horizontalLayout_4.addWidget(self.labelX1)
        self.X1lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X1lineEdit.sizePolicy().hasHeightForWidth())
        self.X1lineEdit.setSizePolicy(sizePolicy)
        self.X1lineEdit.setObjectName("X1lineEdit")
        self.horizontalLayout_4.addWidget(self.X1lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.solveBtn = QtWidgets.QPushButton(self.centralwidget)
        #self.solveBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.solveBtn.setFont(font)
        self.solveBtn.setObjectName("solveBtn")
        self.verticalLayout_3.addWidget(self.solveBtn)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.modeCombo = QtWidgets.QComboBox(self.centralwidget)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modeCombo.sizePolicy().hasHeightForWidth())
        self.modeCombo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.modeCombo.setFont(font)
        self.modeCombo.setFrame(True)
        self.modeCombo.setObjectName("modeCombo")
        self.modeCombo.addItem("")
        self.modeCombo.addItem("")
        #self.modeCombo.addItem("")
        self.verticalLayout_4.addWidget(self.modeCombo)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.solutionText = QtWidgets.QTextEdit(self.centralwidget)
        self.solutionText.setFont(font)
        self.solutionText.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solutionText.sizePolicy().hasHeightForWidth())
        self.solutionText.setSizePolicy(sizePolicy)
        self.solutionText.setObjectName("solutionText")
        self.verticalLayout_4.addWidget(self.solutionText)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prevBtn.setFont(font)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout_11.addWidget(self.prevBtn)
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_11.addWidget(self.nextBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.mplGraph = MplGraph(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplGraph.sizePolicy().hasHeightForWidth())
        self.mplGraph.setSizePolicy(sizePolicy)
        self.mplGraph.setObjectName("mplGraph")
        self.horizontalLayout_2.addWidget(self.mplGraph)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.methodCombo.setItemText(0, _translate("MainWindow", "Choose method to solve"))

        self.methodCombo.setItemText(1, _translate("MainWindow", "Bisection"))
        self.methodCombo.setItemText(2, _translate("MainWindow", "False Bosition"))
        self.methodCombo.setItemText(3, _translate("MainWindow", "Fixed Point"))
        self.methodCombo.setItemText(4, _translate("MainWindow", "Newten "))
        self.methodCombo.setItemText(5, _translate("MainWindow", "Secant"))
        self.methodCombo.setItemText(6, _translate("MainWindow", "Birge Vieta"))
        self.methodCombo.setItemText(7, _translate("MainWindow", "General algorithm"))
        self.methodCombo.setItemText(8, _translate("MainWindow", "All methods"))
        self.label.setText(_translate("MainWindow", "F(x) = "))
        self.label_2.setText(_translate("MainWindow", "                     Select Method                 "))
        self.label_6.setToolTip(_translate("MainWindow", "default : 0.05"))
        self.label_6.setText(_translate("MainWindow", "Eps"))
        self.EpslineEdit.setToolTip(_translate("MainWindow", "default : 0.05"))
        self.EpslineEdit.setText(_translate("MainWindow", ""))
        self.label_5.setToolTip(_translate("MainWindow", "default : 50"))
        self.label_5.setText(_translate("MainWindow", " maximum  Iteration"))
        self.iterlineEdit.setToolTip(_translate("MainWindow", "default : 50"))
        self.iterlineEdit.setPlaceholderText("Default : 50")
        self.labelX0.setText(_translate("MainWindow", "X(0)"))
        self.labelX1.setText(_translate("MainWindow", "X(1)"))
        self.solveBtn.setText(_translate("MainWindow", "Solve"))
        self.solveBtn.setEnabled(False)
        self.modeCombo.setToolTip(_translate("MainWindow", "choose solution mode"))
        self.modeCombo.setItemText(0, _translate("MainWindow", "Direct Solution"))
        self.modeCombo.setItemText(1, _translate("MainWindow", "Single Mode Simulation"))
        #self.modeCombo.setItemText(2, _translate("MainWindow", "Single Mode Simulation(manaul)"))
        self.prevBtn.setText(_translate("MainWindow", "Prev"))
        self.nextBtn.setText(_translate("MainWindow", "Next"))
        self.prevBtn.setEnabled(False)


from mplgraph import MplGraph
